### ISSUE TITLE
adding confidence interval

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#108]
Adding information (score) of confidence interval in addition to accuracy (maybe for classification only).

https://github.com/luferrer/ConfidenceIntervals

**Comment by felixbur** [comment]
sounds interesting, i need to look into it

**Comment by felixbur** [comment]
how about this one?
https://pypi.org/project/confidenceinterval/

**Comment by felixbur** [comment]
actually the computation seems quite simple 
https://machinelearningmastery.com/confidence-intervals-for-machine-learning/
so we could compute that without a library.
If i got it right, you just need the number of test samples and the evaluation measure to compute it

**Comment by hagenw** [comment]
What is more complicated is that for most test sets we usually have several samples per speaker, which means not all samples are independent, and we also need to provide the speaker labels as `conditions` to `evaluate_with_conf_int` from https://github.com/luferrer/ConfidenceIntervals (which was used for Interspeech 2024).

**Comment by felixbur** [comment]
thanks, i start with a version right now that uses the package that Bagus initially suggested

**Comment by felixbur** [comment]
@bagustris please check version 0.81.3 if this is what you had in mind.

**Comment by hagenw** [comment]
You need to add the Python package `confidence_intervals` to the dependencies (`install_requires` section in `setup.cfg`).

**Comment by felixbur** [comment]
thanks, was already there, i just forgot to include it to the github repo

**Comment by bagustris** [comment]
@felixbur Thanks! I tried it with ravdess, and I can see CI in the UAR score. 

We can improve it later.
