### ISSUE TITLE
Option to overwrite (no_reuse) experiment directory

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#136]
In my experience, I often in situations to change EXP.root.name directory due to a previous error  (typo, etc, in the INI file). So, I think it will be convenient to have the "overwrite" or "no_reuse" key in the [EXP] section.  So, with this addition, it will be like the one below.

```
[EXP]
root = ./apsipa_2024/results/
name = exp_turev_audmodel_32
no_reuse = true
```
The default should be 'false' to meet current behavior. With `true`, all files inside root.name will be erased to start new experiment. How  @felixbur?

**Comment by felixbur** [comment]
this sounds like a combination of
```
[DATA}
no_reuse = True
{FEATS]
```
but, yes, why not. Shall i implement it?

no_reuse = True

**Comment by bagustris** [comment]
@felixbur 
I don't realize if [DATA] has `no_reuse` key too. I checked it works as my need, so maybe no need to implement.
