### ISSUE TITLE
Change development and GH action to use python3.9

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#140]
Until now, I have used Python 3.8 to check Nkululeko functionalities, including the GitHub action.

Since python3.8 will reach end-of-life this year's October (2024/10), I plan to move to use python3.9 as my default python, including testing Nkululeko functionalities.

https://devguide.python.org/versions/

The current python3.8 version prevents to update newer packages, e.g, speechbrain>=1.0 which is used by feats_spkrec.py.

**Comment by felixbur** [comment]
i use, since longer, python 3.10
that's fine with you too?
