### ISSUE TITLE
Feature request: save plots in several different formats

### ISSUE THREAD

**Issue by Pascal-H** [felixbur/nkululeko#151]
I have the habit of exporting plots in different formats, so that I have a `.png` file at hand easily for quick inspection, but in addition, I like to have also `.pdf` files of a plot to embed them with LaTeX in a publication, as well as `.eps` files to be able to edit the vector-based "ground truth" in case I need to change the axis label or so afterwards.  
Respectively, I tried  
```
[EXPL]
format = [png, pdf, svg]
```  
But got the error:  
`ValueError: Format '[png, pdf, svg]' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff, webp)
`  

Also  
```
[EXPL]
format = ["png", "pdf", "svg"]
```
did not work.

In my projects, I usually do something like  
```
# Save the figure
for cur_extension in [".png", ".pdf", ".svg"]:
    cur_fig.savefig(
        os.path.join(
            self.path_plots, f"confmat-{cur_set}{cur_extension}"
        ),
        bbox_inches="tight",
    )
plt.close(cur_fig)
```

**Comment by felixbur** [comment]
you are aware there already is a plot format option?
https://github.com/felixbur/nkululeko/blob/main/ini_file.md#plot
[PLOT]
format = [png | eps]

**Comment by Pascal-H** [comment]
Ah perfect, that might solve it. As  I showed above, I tried  
`format = [png, pdf, svg]`, but if `format = [png | eps]` is the correct syntax, then this shouldn't be an issue :sunglasses:

**Comment by felixbur** [comment]
and you need to use the PLOT section

**Comment by felixbur** [comment]
but of course i don't see a reason not to add svg and pdf to the list, if that's supported by matplotlib. so let's leave this issue open

**Comment by Pascal-H** [comment]
Hmm, I just ran this config  

```
[EXP]
root = ./sandbox-emodb/
name = sandbox-emodb-explore-scatter
[DATA]
databases = ['emodb']
emodb = ./sandbox-emodb/emodb/
target = emotion
# FEATS and MODEL have to be given, even if not used
[FEATS]
type = ['os']
[MODEL]
n_jobs = 10
type = xgb
[PLOT]
format = [png | pdf | svg]
```

And I still get
```
    raise ValueError(              
ValueError: Format '[png | pdf | svg]' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff, webp)
```

According to the error, PDF and SVG should already be supported :thinking:

**Comment by felixbur** [comment]
You need to write 
format=eps

**Comment by bagustris** [comment]
I tested it works with SVG below, so we can close this issue.

```INI
[EXP]
root = ./tests/results/
name = exp_polish_os
[DATA]
databases = ['train', 'dev', 'test']
train = ./data/polish/polish_train.csv
train.type = csv
train.absolute_path = False
train.split_strategy = train
; train.audio_path = ./POLISH
dev = ./data/polish/polish_dev.csv
dev.type = csv
dev.absolute_path = False
dev.split_strategy = train
; dev.audio_path = ./POLISH
test = ./data/polish/polish_test.csv
test.type = csv
test.absolute_path = False
test.split_strategy = test
target = emotion
[FEATS]
type = ['os']
; type = ['hubert-xlarge-ll60k']
; no_reuse = False
; scale = standard
[MODEL]
type = bayes
; save = True
[RESAMPLE]
replace = True
[PLOT]
format = SVG
```

**Comment by felixbur** [comment]
perfect
