### ISSUE TITLE
[FEATURE REQUEST] currently there is no prediction file from finetuning model

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#160]
**Why do you propose this feature?**
Other models like SVM, XGB, and MLP already have prediction files (`pred_xxxx.csv`) under the `store` directory but no prediction file from the fine-tuning model.

**Describe the solution you'd like**
By default, fine-tuning model should output the prediction file as others , so it can be used for further analysis (e.g., ensemble)

**Comment by bagustris** [comment]
@felixbur, could you look into this when you have time? Since [you make the original prediction files](https://github.com/felixbur/nkululeko/issues/103#issuecomment-2178400588_
            ) for models other than fine tuning models, If there is a clue on this issue, I may work on #150 .

**Comment by felixbur** [comment]
i look into it

**Comment by felixbur** [comment]
done with version 0.90.2

**Comment by bagustris** [comment]
Confirmed it now works, closing the issue!
