### ISSUE TITLE
Google colab for tutorial

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#29]
Provide tutorial on EmoDB, ravdess, and Crema-D using Google Colab and/or Kaggle.
Put under the docs.

**Comment by bagustris** [comment]
I make working example in Google Colab here,

https://colab.research.google.com/drive/1GYNBd5cdZQ1QC3Jm58qoeMaJg3UuPhjw?usp=sharing
]

**Comment by felixbur** [comment]
Super, thanks!

**Comment by felixbur** [comment]
Done: https://github.com/felixbur/nkululeko#hello-world-example

**Comment by felixbur** [comment]
I will later do this on Kaggle

**Comment by felixbur** [comment]
Done
https://www.kaggle.com/felixburk/nkululeko-hello-world-example
