### ISSUE TITLE
Error on plotting gender models

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#50]
When I run the following commands, 

    python -m nkululeko.explore --config tests/exp_emodb_explore_data.ini

I got the following error:

    ERROR plots: plot value counts: target gender has more than 2 values

I think the error is caused by the fact that Audeering models' resulted in three gender values instead of two, maybe.

**Comment by felixbur** [comment]
fixed in version 0.55.1
i got the error: i changed the format of the plot distribution descriptors
needs to be  [[gender],[age]] as opposed to [gender, age]
