### ISSUE TITLE
Resample issues (need target, split, etc)

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#72]
Module `nkululeko.resample` should need `file` only to resample, but currently it needs splitting strategy and target. Hence, the ideal minimum INI file would be the following

```INI
[DATA]
databases = ['train']
train = ./data/enterface/enterface_avi.csv
train.type = csv
train.absolute_path = False
[RESAMPLE]
sample_selection = all
```

Without the need other sections (EXP, MODEL, FEATS, etc.).

Btw, it will also be helpful to add an option to backup original data to the RESAMPLE section (e.g., by providing option `backup_original = True`) to compressed file (via `nkululeko.export` ?).

**Comment by felixbur** [comment]
totally agree there should be a way to resample but keep the originals. 
and i think this should be default

**Comment by felixbur** [comment]
> Module `nkululeko.resample` should need `file` only to resample, but currently it needs splitting strategy and target. Hence, the ideal minimum INI file would be the following
> 
> ```ini
> [DATA]
> databases = ['train']
> train = ./data/enterface/enterface_avi.csv
> train.type = csv
> train.absolute_path = False
> [RESAMPLE]
> sample_selection = all
> ```
> 
> Without the need other sections (EXP, MODEL, FEATS, etc.).
> Module nkululeko.resample should need file only to resample, but currently it needs splitting strategy and target. Hence, the ideal minimum INI file would be the following

Actually i think that is already the case.
You don't even need that, you can simply call the resample module on some config and it should resample all in train and test split to 16 kHz. just note it's NOT necessarily the whole database, but only the train and test splits

**Comment by bagustris** [comment]
I tested the newest main branch, it still gives me error when I don't give it [EXP] and `target`.

In case of missing `[EXP]`
```
Traceback (most recent call last):
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bagus/github/nkululeko/nkululeko/resample.py", line 63, in <module>
    main(cwd) # use this if you want to state the config file path on command line
  File "/home/bagus/github/nkululeko/nkululeko/resample.py", line 31, in main
    expr = Experiment(config)
  File "/home/bagus/github/nkululeko/nkululeko/experiment.py", line 38, in __init__
    self.name = glob_conf.config["EXP"]["name"]
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'EXP'
```

In case of missing `target`
```
(nkululeko) bagus@pc-omen:nkululeko$ python3 -m nkululeko.resample --config data/enterface/exp_resample2.ini 
DEBUG resample: running results/exp_enterface_aud from config data/enterface/exp_resample2.ini, nkululeko version 0.65.5
Traceback (most recent call last):
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bagus/github/nkululeko/nkululeko/resample.py", line 63, in <module>
    main(cwd) # use this if you want to state the config file path on command line
  File "/home/bagus/github/nkululeko/nkululeko/resample.py", line 40, in main
    expr.load_datasets()
  File "/home/bagus/github/nkululeko/nkululeko/experiment.py", line 69, in load_datasets
    data = Dataset_CSV(d)
  File "/home/bagus/github/nkululeko/nkululeko/data/dataset.py", line 31, in __init__
    self.target = glob_conf.config["DATA"]["target"]
  File "/home/bagus/miniconda3/envs/nkululeko/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'target'
```

Btw, I made a PR #74 to force resample to save as WAV file (in case the original files are not in wav, it won't be overwritten) and handle file names with spaces.

**Comment by felixbur** [comment]
ah: i see. yes, until now every experiment needs a EXP section and a target key.
i think at least the experiment name (in the EXP section) is not optional, as we need some root directory for all processing

**Comment by bagustris** [comment]
Thanks!

One more, Resample should also offer to convert stereo to mono (maybe by default, since the default is already back up the original data). The stereo file will make errors since the size of the acoustic feature will be twice as other (eg, in speaker embedding). 

Currently, I convert mono to stereo on the feature extraction stage (after resample).

**Comment by felixbur** [comment]
yes, makes sense.
I think the RESAMPLE module should simply get a flag
check_channels = True|False
and depending on this, convert to Mono if necessary.
I could do this later
