### ISSUE TITLE
Support for data balancing

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#88]
Data balancing is important for machine learning.

I would to propose the following feature:

```INI
[DATA]
balancing = True # default false
balancing_strategy = ros # options: ros, smote, adasyn
```

There is currently [imbalanced-learn](https://imbalanced-learn.org/) package that is contrib package of scikit-learn. However, no need to stick in this package (can be defined in `balancing_strategy` above).

**Comment by felixbur** [comment]
yes, makes sense, i used to work with the imbalance learn package some years ago
i wanted to wait until my pal Uwe releases his stratification package, but that might take too long, so we could go ahead with imbalanced-learn

**Comment by felixbur** [comment]
I guess that would be a special filter to be set in experiment class as a post-processing step to feature extraction

**Comment by felixbur** [comment]
for shortness I'd prefer
```
[DATA]
balancing = ros # options: ros, smote, adasyn
```

**Comment by felixbur** [comment]
Done with version 0.70.0
